apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-okxwszya
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-okxwszya:2aed5912ff909abe99e2759eb77a95fccb202fdf@sha256:133b78bf7f1979588aa431cb96dc63f189aa0ce0a90e9a75f374561b95398756
          name: container-image
